modLoader = "javafml" #mandatory
loaderVersion = "${loader_version_range}" #mandatory
license = "${mod_license}"

[[mods]] #mandatory
modId = "${mod_id}" #mandatory
version = "${mod_version}" #mandatory
displayName = "${mod_name}" #mandatory
authors = "${mod_authors}" #optional
description = '''${mod_description}'''

# 1. Forge 의존성
[[dependencies."${mod_id}"]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

# 2. 마인크래프트 의존성
[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

# 3. GeckoLib 의존성 (분리 및 버전에 맞게 수정)
[[dependencies."${mod_id}"]]
modId = "geckolib"
mandatory = true
versionRange = "[4.8.2,)"
ordering = "BEFORE"
side = "BOTH"